
import React, { useState, useEffect } from 'react';
import { Product, Category } from '../types';
import { api } from '../services/api';
import ProductCard from '../components/ProductCard';

const SETUP_SQL = `
-- COPY AND RUN THIS IN SUPABASE SQL EDITOR

-- 1. Create Core Tables
create table if not exists units (
  id serial primary key,
  name text not null
);

create table if not exists categories (
  id serial primary key,
  name text not null,
  "categoryCode" text not null
);

create table if not exists users (
  id serial primary key,
  "fullName" text not null,
  email text not null,
  password text not null,
  role text not null,
  location text,
  "identityCardUrl" text,
  "identityCardStatus" text,
  "digitalWalletProvider" text,
  "digitalWalletBalance" numeric
);

create table if not exists suppliers (
  id serial primary key,
  "userId" integer references users(id),
  status text not null,
  "supplierCode" text not null,
  "companyName" text not null,
  address text,
  "phoneNumber" text,
  "salesName" text
);

create table if not exists products (
  id serial primary key,
  name text not null,
  description text,
  "costPrice" numeric not null,
  "sellingPrice" numeric not null,
  stock integer not null default 0,
  barcode text,
  "imageUrl" text,
  "categoryId" integer references categories(id),
  "unitId" integer references units(id),
  specifications jsonb,
  "discountPercent" numeric,
  "priceTiers" jsonb,
  sku text,
  "supplierCode" text,
  "supplierId" integer references suppliers(id)
);

-- 2. Shipping & Order Management
create table if not exists orders (
  id text primary key,
  "userId" integer references users(id),
  items jsonb not null,
  total numeric not null,
  "paymentMethod" text not null,
  date timestamptz not null,
  "bankName" text,
  "digitalWalletProvider" text,
  "shippingAddress" text,
  "shippingProviderId" integer references users(id),
  "shippingStatus" text,
  "trackingNumber" text,
  "applicationFee" numeric
);

-- 3. Purchasing & Inventory
create table if not exists purchases (
  id text primary key,
  "productId" integer references products(id),
  "productName" text,
  quantity integer not null,
  "purchasePrice" numeric not null,
  "totalCost" numeric not null,
  date timestamptz not null
);

-- 4. Site Settings & Configuration
create table if not exists site_settings (
  id integer primary key generated by default as identity,
  "logoUrl" text,
  "enabledPaymentMethods" jsonb,
  "enabledBanks" jsonb,
  "enabledDigitalWallets" jsonb,
  "bankDetails" jsonb,
  "lowStockThreshold" integer,
  "applicationFee" numeric
);

-- 5. CMS (About Page)
create table if not exists about_page (
  id integer primary key generated by default as identity,
  title text,
  subtitle text,
  "visionTitle" text,
  "visionText" text,
  "missionTitle" text,
  "missionItems" jsonb,
  "historyTitle" text,
  "historyText" text,
  "galleryTitle" text,
  "galleryImages" jsonb,
  "locationTitle" text,
  "locationMapUrl" text
);

-- 6. Insert Default Data (Safe to run multiple times)
INSERT INTO units (name) VALUES ('Pcs'), ('Kg'), ('Dus'), ('Pak') ON CONFLICT DO NOTHING;
INSERT INTO categories (name, "categoryCode") VALUES ('Makanan', 'FOD'), ('Minuman', 'BVG'), ('Sembako', 'GRC') ON CONFLICT DO NOTHING;
-- Password is 'password'
INSERT INTO users ("fullName", email, password, role) VALUES ('Super Admin', 'superadmin@test.com', 'password', 'SUPER_ADMIN') ON CONFLICT DO NOTHING;

-- Initialize Settings if empty
INSERT INTO site_settings (id, "lowStockThreshold", "applicationFee", "logoUrl") 
SELECT 1, 5, 0, '/logo.svg' 
WHERE NOT EXISTS (SELECT 1 FROM site_settings WHERE id = 1);
`;

const HomePage: React.FC = () => {
  const [products, setProducts] = useState<Product[]>([]);
  const [categories, setCategories] = useState<Category[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('');
  const [sortBy, setSortBy] = useState('');
  
  // State for database setup error
  const [dbError, setDbError] = useState<string | null>(null);

  useEffect(() => {
    const loadData = async () => {
      setLoading(true);
      setDbError(null);
      try {
        const [fetchedProducts, fetchedCategories] = await Promise.all([
          api.fetchProducts(),
          api.fetchCategories()
        ]);
        setProducts(fetchedProducts);
        setCategories(fetchedCategories);
      } catch (error: any) {
        console.error("Failed to load data", error);
        // Check for common Supabase "missing table" errors
        const errMsg = error.message || '';
        if (
            errMsg.includes('Could not find the table') || 
            errMsg.includes('relation') || 
            errMsg.includes('does not exist') ||
            errMsg.includes('schema cache')
        ) {
           setDbError(errMsg);
        }
      } finally {
        setLoading(false);
      }
    };
    loadData();
  }, []);

  useEffect(() => {
    const handleSearch = async () => {
        // Skip search if we already know DB is missing
        if (dbError) return;

        setLoading(true);
        try {
            const categoryId = selectedCategory ? parseInt(selectedCategory, 10) : undefined;
            const results = await api.searchProducts(searchTerm, categoryId, sortBy);
            setProducts(results);
        } catch (error: any) {
            console.error("Failed to search products", error);
             // Don't override main DB error if it's already set, but set it if it happens here
             const errMsg = error.message || '';
             if (errMsg.includes('Could not find the table') || errMsg.includes('relation')) {
                setDbError(errMsg);
             }
        } finally {
            setLoading(false);
        }
    }
    const timer = setTimeout(() => {
        handleSearch();
    }, 300); // Debounce search
    return () => clearTimeout(timer);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchTerm, selectedCategory, sortBy]);

  const copyToClipboard = () => {
    navigator.clipboard.writeText(SETUP_SQL);
    alert('SQL script copied to clipboard! Paste it into your Supabase SQL Editor.');
  };

  if (dbError) {
    return (
        <div className="max-w-4xl mx-auto mt-10 p-6 bg-white rounded-lg shadow-xl border border-red-200">
            <div className="text-center mb-6">
                <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-red-100 mb-4">
                    <svg className="w-8 h-8 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
                </div>
                <h2 className="text-2xl font-bold text-gray-800">Database Belum Siap</h2>
                <p className="text-gray-600 mt-2">Aplikasi gagal terhubung ke tabel database. Kemungkinan tabel belum dibuat di Supabase.</p>
                <p className="text-red-500 text-sm mt-2 font-mono bg-red-50 py-1 px-2 inline-block rounded">{dbError}</p>
            </div>

            <div className="bg-gray-800 rounded-lg p-4 overflow-x-auto relative">
                <div className="flex justify-between items-center mb-2 text-gray-400 text-xs uppercase font-semibold tracking-wider">
                    <span>SQL Setup Script</span>
                    <button 
                        onClick={copyToClipboard}
                        className="bg-primary hover:bg-primary-hover text-white px-3 py-1 rounded text-xs transition-colors"
                    >
                        Copy SQL
                    </button>
                </div>
                <pre className="text-green-400 font-mono text-sm whitespace-pre">{SETUP_SQL}</pre>
            </div>

            <div className="mt-6 text-center">
                <p className="text-gray-700 mb-4">
                    <strong>Cara Memperbaiki:</strong>
                    <ol className="list-decimal list-inside mt-2 text-left max-w-md mx-auto space-y-2">
                        <li>Copy script SQL di atas.</li>
                        <li>Buka Dashboard Supabase Anda.</li>
                        <li>Masuk ke menu <strong>SQL Editor</strong>.</li>
                        <li>Paste script dan klik <strong>Run</strong>.</li>
                        <li>Refresh halaman ini.</li>
                    </ol>
                </p>
                <button 
                    onClick={() => window.location.reload()}
                    className="bg-primary text-white font-bold py-2 px-6 rounded hover:bg-primary-hover"
                >
                    Refresh Halaman
                </button>
            </div>
        </div>
    );
  }

  return (
    <div>
      <div className="bg-surface p-4 rounded-lg shadow-sm mb-8">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 items-center">
            <select
                value={selectedCategory}
                onChange={(e) => setSelectedCategory(e.target.value)}
                className="w-full p-2 bg-white border border-gray-300 rounded-md focus:ring-primary focus:border-primary"
            >
                <option value="">Semua Kategori</option>
                {categories.map(cat => (
                    <option key={cat.id} value={cat.id}>{cat.name}</option>
                ))}
            </select>
            <input
                type="text"
                placeholder="Cari nama barang..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full p-2 bg-white border border-gray-300 rounded-md focus:ring-primary focus:border-primary"
            />
            <select
                value={sortBy}
                onChange={(e) => setSortBy(e.target.value)}
                className="w-full p-2 bg-white border border-gray-300 rounded-md focus:ring-primary focus:border-primary"
            >
                <option value="">Urutkan</option>
                <option value="price-asc">Harga: Terendah</option>
                <option value="price-desc">Harga: Tertinggi</option>
                <option value="name-asc">Nama: A-Z</option>
            </select>
        </div>
      </div>

      {loading ? (
        <div className="text-center py-10">
          <p className="text-lg">Memuat produk...</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          {products.length > 0 ? (
            products.map(product => (
              <ProductCard key={product.id} product={product} />
            ))
          ) : (
             <div className="col-span-full text-center py-10">
                <p className="text-lg text-gray-500">Produk tidak ditemukan.</p>
             </div>
          )}
        </div>
      )}
    </div>
  );
};

export default HomePage;
